### ISSUE TITLE
[TASK] Architecting networking layer and unimplemented work for zkSaaS

### ISSUE THREAD

**Issue by shekohex** [webb-tools/zk-SaaS#5]
# Overview
There's likely a lot in this repo that doesn't mesh with our existing architecture. We should identify them and implement what we can.
- https://github.com/guruvamsi-policharla/zksaas

## Tasks
- [ ] Identify existing networking zkSaaS uses (it's likley for demo purposes)
- [ ] Identify if we want to implement MpcNet
- [ ] Implement MpcNet or solution.
- [ ] Identify how the existing distributed protocols work, and how we can best architect them for the future.
